### ISSUE TITLE
Group booking ?

### ISSUE THREAD

**Issue by sarathbp** [mahdiaredraki/Automated-US-Visa-Appointment-Finder#1]
Will it support group booking - with more than one person in the appointment ?

**Comment by mahdiaredraki** [comment]
I haven't tried that because in my case it was a single applicant. But I don't see a reason why it wouldn't work with group booking. Let me know if you have trouble running the application and I'd be happy to help troubleshoot.

**Comment by sarathbp** [comment]
I have an appointment for my family(me, wife and daughter). It is logging me out at the member selection page.
