### ISSUE TITLE
NameError: name 'Selected_city_cdoe' is not defined.

### ISSUE THREAD

**Issue by kjhelpme** [mahdiaredraki/Automated-US-Visa-Appointment-Finder#2]

**Comment by kjhelpme** [comment]
I tried to run the code and it asks to select my country, login details, year for appointment (2024), and month for appointment (August). 

The error I receive after filling these out is 

NameError: name 'Selected_city_code' is not defined. Did you mean: 'Selected_country_code"?
[3088] Failed to execute script 'US_Visa_Appointment_Bot' due to unhandled exception!

**Comment by mahdiaredraki** [comment]
Hmm, what country and city are you applying through?

**Comment by kjhelpme** [comment]
I selected Turkey. It didn't give me a city option, but I want to do the Ankara Embassy

**Comment by mahdiaredraki** [comment]
Send me an email edrakimahdiar@gmail,com and we can get it sorted out.
