### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by ReLoadTR** [mahdiaredraki/Automated-US-Visa-Appointment-Finder#3]
.exe not work. Directly closing

**Comment by lufees** [comment]
Similar issue on my side as well, would you happen to know what is the reason for the issue

**Comment by ReLoadTR** [comment]
> Similar issue on my side as well, would you happen to know what is the reason for the issue

I didn't try again to get it working.

**Comment by mahdiaredraki** [comment]
Make sure you have downloaded the chromedriver and placed it in the same directory as the .exe
